# Generated by Django 3.2 on 2021-05-01 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_student_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('REK', 'Rekrutacja'), ('INN', 'Inne')], default='REK', max_length=3)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(default=0.4)),
                ('askedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asked_questions', to=settings.AUTH_USER_MODEL)),
                ('universities', models.ManyToManyField(to='system.University')),
            ],
        ),
    ]
